# Generated by Django 5.2.7 on 2025-10-14 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_arquivo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arquivo',
            new_name='File',
        ),
    ]
