# Generated by Django 5.2.7 on 2025-10-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_rename_arquivo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extension',
            new_name='ext',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_weight',
            new_name='size',
        ),
    ]
