# Generated by Django 5.2.7 on 2025-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_rename_extension_file_ext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default='/', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='ext',
            field=models.CharField(max_length=200),
        ),
    ]
