# Generated by Django 5.2.7 on 2025-10-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_file_path_alter_file_ext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.CharField(max_length=200),
        ),
    ]
