# Generated by Django 5.2.7 on 2025-10-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0006_alter_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ext',
        ),
    ]
