# Generated by Django 5.2.7 on 2025-10-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0007_remove_file_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
    ]
