# Generated by Django 5.2.7 on 2025-10-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0008_remove_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
