# Generated by Django 5.2.7 on 2025-10-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0009_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
